FROM nginx:alpine

# Check if the www-data group exists; if not, create it
RUN getent group www-data || addgroup -g 33 www-data

# Check if the www-data user exists; if not, create it
RUN getent passwd www-data || adduser -u 33 -G www-data -D www-data

# Copy your nginx configuration
COPY ./docker-files/nginx/nginx.conf /etc/nginx/nginx.conf

# Ensure the correct permissions for the web root
RUN mkdir -p /var/www && chown -R www-data:www-data /var/www

# Expose port
EXPOSE 80
